public with sharing class Constants {
	public static final String UPSELL_LIFT = 'Up-Sell/Lift';
	public static final String OP_STAGE_SIGNED_IN = '5 - Signed/PO in';
	public static final String OP_STAGE_SETUP = '6 - Setup';
	public static final String OP_STAGE_CLOSED= '7 - Closed';
	public static final String OP_STAGE_LOST= 'Lost';
	public static final String OP_STAGE_DEAD= 'Dead';
	public static final STring SENT_TO_NCSP = 'Sent to NCSP';
	
}