/****************************** 
   Developer Name    : Madhu Paladugu
   
   Date              : 10/18/13
   
   Company Name      : CloudFountain Inc.
   
   Purpose           : This class is used as test utility for CDM_Utility class. 
   
   Dependents        : Apex Class  : CDM_Utility 
   
   Case Number       : 01733573
                                  
 ********************************/ 

@isTest//(seeAllData=true)
public class Test_CDM_Utility{
 /*   
    public static TestMethod void doTest(){
          
        IM_Country__c c = new IM_Country__c(name='United States');
        insert c;
        
        //create dummy account
        Account a=new Account(Name='test',type='Customer',BillingCountry='United States',IM_Sales_Segment__c='Channel',BillingStreet='683 c',BillingCity='Boston',BillingState='MA',BillingPostalCode='02120',IM_DUNS_NBR__c='test');
        insert a;
        
        List<Account> AccountList=new List<Account>();
        AccountList.add(a);
        String message='Test';
        
        //cal methods for test coverage
        CDM_Utility.feedRegularPost(message,AccountList);
        CDM_Utility.feedCSVfilePost(message,AccountList);
    }
*/
}