@isTest
public class Test_Q2W_UpdateQuotStage {
  /*  
       Static TestMethod void doTest(){
       Q2W_Quote_Stage_Progre_BatchJob b=new Q2W_Quote_Stage_Progre_BatchJob('test');
       Test.starttest();   
       Database.executeBatch(b,200);
       Test.stoptest();
    }
       Static TestMethod void doTest1(){
       Q2W_UpdateQuotStage_SchdleClas b1=new Q2W_UpdateQuotStage_SchdleClas();
       Test.starttest();   
       b1.execute(null);
       Test.stoptest();
    }

 */
}